on:
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.ARCHE_GITHUB_PKG_REGISTRY }}
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and upload arche docker image
    steps:
      - name: Login to JFrog
        uses: docker/login-action@v1.9.0
        with:
          registry: jfrog.dev.hub.vwgroup.com
          username: ${{ secrets.JFROG_DEPLOY_USER }}
          password: ${{ secrets.JFROG_DEPLOY_TOKEN }}
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v2
        
      - name: Import image in containerd
        run: |
          sudo ctr image pull releases-docker.jfrog.io/jfrog/artifactory-pro:7.46.6
       
      - name: List Images
        run: |
          sudo ctr images ls
          
      - name: Import tag in containerd
        run: |
          sudo ctr i tag releases-docker.jfrog.io/jfrog/artifactory-pro:7.46.6 jfrog.dev.hub.vwgroup.com/amt-docker-internal/github.com-test/artifactory:1.0
      - name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ secrets.JFROG_DEPLOY_USER }}:${{ secrets.JFROG_DEPLOY_TOKEN }}" jfrog.dev.hub.vwgroup.com/amt-docker-internal/github.com-test/artifactory:1.0
  #    - name: Build and push docker image
  #      uses: docker/build-push-action@v2.4.0
  #      with:
  #        file: Dockerfile
  #        push: true
  #        tags: jfrog.dev.hub.vwgroup.com/amt-docker-internal/jfrog/artifactory:1.x
