name: Build and push JPD images

on:
  workflow_dispatch:

jobs:

  docker_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: login to Jfrog registry
      run: |
        docker login -u ${{ secrets.JFROG_DEPLOY_USER }} -p ${{ secrets.JFROG_DEPLOY_TOKEN }} jfrog.dev.hub.vwgroup.com
    #- name: Build the image (TAG specified as input)
    #  run: |
    #    sudo ctr build \
    #      -t jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory:1.0 \
    #      --format=docker \
    #      -f Dockerfile .
      
    - name: Build the image (TAG specified as input)
      run: |
        docker build \
          -t jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory:latest \
          -f Dockerfile .
    - name: List the docker images
      run: docker save --output artifactory.tar jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory:latest
    
    - name: Docker check manifest
      run: docker manifest inspect jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory:latest
    
    - name: import the docker images
      run: sudo ctr i import --base-name jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory --digests --all-platforms artifactory.tar
    
    - name: List the docker images
      run: sudo ctr images ls

    - name: Run buildah push
      run: sudo ctr i push --user "${{ secrets.JFROG_DEPLOY_USER }}:${{ secrets.JFROG_DEPLOY_TOKEN }}" "jfrog.dev.hub.vwgroup.com/amt-docker-releases/test/artifactory:1.0"
